version: "3.9"
services:
  web:
    build: .
    container_name: openmahalla-web
    command: >
      bash -c "
        python3 manage.py migrate &&
        python3 manage.py collectstatic --no-input &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8001 --workers 1 --timeout 300 --log-level DEBUG
      "
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    expose:
      - "8001"

  rabbitmq:
    image: rabbitmq:management
    container_name: openmahalla-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5673:5672"
      - "15673:15672"

  redis:
    image: redis:latest
    container_name: openmahalla-redis
    ports:
      - "6380:6379"

  celery:
    build: .
    container_name: openmahalla-celery
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - redis
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    container_name: openmahalla-nginx
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web

volumes:
  static_volume: